name: Autobump Formulas and Casks

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  autobump:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN || github.token }}
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@dfa608a07e77f96aa34d0c8a35fc62efa863417f # Homebrew 5 compatibility
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN || github.token }}
          user_name: Neved4
          user_email: 63655535+Neved4@users.noreply.github.com
          no_fork: true
          tap: Neved4/homebrew-tap
          force: true
          livecheck: true
      - name: Update Homebrew cask
        if: ${{ always() }}
        uses: eugenesvk/action-homebrew-bump-cask@4fd4f2a0dd6b9b4faeb02b790bbab185c5ebf79d # Homebrew 5 compatibility
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN || github.token }}
          tap: Neved4/homebrew-tap
          livecheck: true
