name: Autobump Formulas and Casks

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  autobump:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN || github.token }}
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@df4b09108a1de9d6f995fe68f302b3f68bd6d2ef # 2026-07-17
      - name: Configure git
        run: |
          git config --global user.name Neved4
          git config --global user.email 63655535+Neved4@users.noreply.github.com
      - name: Autobump formulae
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN || github.token }}
        run: |
          brew livecheck --formula --newer-only --full-name --json --tap=Neved4/homebrew-tap \
            | jq -r '.[] | select(.version.outdated == true) | [.formula, .version.latest] | @tsv' \
            | while IFS=$'\t' read -r formula version; do
                brew bump-formula-pr --no-audit --no-browse --version="$version" "$formula"
              done
      - name: Autobump casks
        if: ${{ always() }}
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN || github.token }}
        run: |
          brew livecheck --cask --newer-only --full-name --json --tap=Neved4/homebrew-tap \
            | jq -r '.[] | select(.version.outdated == true) | [.cask, .version.latest] | @tsv' \
            | while IFS=$'\t' read -r cask version; do
                brew bump-cask-pr --no-audit --no-browse --version="$version" "$cask"
              done
