name: Add pr-pull label to merge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened

jobs:
  check-for-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            src:
              - 'Formula/**'

      # unclear why `github.event_name == 'pull_request'` is required but it is
      - run: exit 0
        if: steps.changes.outputs.src == 'false' || (github.event_name == 'pull_request' && contains( github.event.pull_request.labels.*.name, 'pr-pull' ))

      - run: exit 1
        if: steps.changes.outputs.src == 'true' && github.event_name == 'pull_request' && !contains( github.event.pull_request.labels.*.name, 'pr-pull' )
